export enum ETxType {
  ADD_SIGNER = 'ADD_SIGNER',
  REMOVE_SIGNER = 'REMOVE_SIGNER',
  STAKE = 'STAKE',
  CONTRACT_INTERACTION = 'CONTRACT_INTERACTION',
  SWAP_ORDER = 'SWAP_ORDER',
  NFT_TRANSFER = 'NFT_TRANSFER',
  TOKEN_TRANSFER = 'TOKEN_TRANSFER',
}
