export enum ETxType {
  ADD_SIGNER = 'ADD_SIGNER',
  REMOVE_SIGNER = 'REMOVE_SIGNER',
  STAKE_DEPOSIT = 'STAKE_DEPOSIT',
  STAKE_WITHDRAW_REQUEST = 'STAKE_WITHDRAW_REQUEST',
  STAKE_EXIT = 'STAKE_EXIT',
  CONTRACT_INTERACTION = 'CONTRACT_INTERACTION',
  SWAP_ORDER = 'SWAP_ORDER',
  NFT_TRANSFER = 'NFT_TRANSFER',
  TOKEN_TRANSFER = 'TOKEN_TRANSFER',
  VAULT_DEPOSIT = 'VAULT_DEPOSIT',
  VAULT_REDEEM = 'VAULT_REDEEM',
  CANCEL_TX = 'CANCEL_TX',
}
