export enum ETxType {
  ADD_SIGNER = 'ADD_SIGNER',
  REMOVE_SIGNER = 'REMOVE_SIGNER',
  STAKE_DEPOSIT = 'STAKE_DEPOSIT',
  CONTRACT_INTERACTION = 'CONTRACT_INTERACTION',
  SWAP_ORDER = 'SWAP_ORDER',
  NFT_TRANSFER = 'NFT_TRANSFER',
  TOKEN_TRANSFER = 'TOKEN_TRANSFER',
  VAULT_DEPOSIT = 'VAULT_DEPOSIT',
  VAULT_REDEEM = 'VAULT_REDEEM',
}
